POST http://localhost:3001/api/entries/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbmlzYW5jaGV6LmRldkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCROOENmbEdzMjhaNndXTEtTVDh6ZTh1cldHcVh4eHdWZkhBNWljV1hhS09vbVk3TndaWlhlQyIsImlhdCI6MTcwNTAzNzQ0OX0.xr6m04v975P3KZ7r2JReqFyk2XvXbxHifAhmwwNw-wQ

{
  "field1": "Hello World",
  "field2": 47
}

// Before testing use log in endpoint to get a new token.
// Expect a 422 with the mongoose error message.
