POST http://localhost:3000/api/entries/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbmlzYW5jaGV6LmRldkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQwenJ1cmRZLkN4Z0c2THA5bS5IMkt1Q01Bb3lZZXFOcW9WaTE4NTlVYlFhSklMcWcvUGh3eSIsImlhdCI6MTY0NzQ0NDg2Mn0.RRVCdQkFbYatAhSa3k5XIDTYG3bNHE3d-GctwyB8O1U

{
  "field1": "Hello World",
  "field2": 47
}

// Before testing use log in endpoint to get a new token.
